### ISSUE TITLE
Frame hitches and lag

### ISSUE THREAD

**Issue by DevBlocky** [blockba5her/dispatchsystem#13]
Reports of lag whenever a function executed in DispatchSystem.
**# of reports: 1**

Report hardware specs:
6GB
300 GB storage
3 core CPU, unknown CPU variant (prob AMD because I don't think Intel makes 3 core chips)
Windows 2012 Server OS

Probable cause: Lack of multi-threading could case while, for, and each loops to slow down PC hardware, and also cause threading to be very slow for CPU to handle. This could be a main issue with the CloNET server side, more details have to be provided first though.

More updates will be posted in the comment section about the diagnostics.

**Comment by DevBlocky** [comment]
Via response of `Blizzard#5195` on discord, it seems as if CloNET seems to be the cause of the issue with too many loops happening at once, overwhelming the PC.

@Clone-Commando Anything you can do?

**Comment by malicean** [comment]
Perhaps. The only big loop is the data-checking loop. Refresh rate is at 1 ms for lowest latency but i could make it adjustable.

**Comment by DevBlocky** [comment]
Update: Clone is going to update his CloNET module to add a lower refresh rate to slow down server transactions and keep the looping to a minimum. Hopefully within a week a public beta should be out with this feature :)

**Comment by DevBlocky** [comment]
Working on net event queues and suck have solved somewhat of the frame hitches.

Reference commits for queue implementations
[418950e](https://github.com/DispatchSystems/DispatchSystem/commit/418950eb76da1e4aa82eee7ed44408cfcdd0956b) [e6a343a](https://github.com/DispatchSystems/DispatchSystem/commit/e6a343a2ed4fc371096f2ae7c9b7af83b97e7a3b) [9fab707](https://github.com/DispatchSystems/DispatchSystem/commit/9fab70755e9c7c626d4a017a44f9b751f9983d66)

**Comment by DevBlocky** [comment]
This (I think) should be fixed in the above commits.
