### ISSUE TITLE
Commands stop working after used

### ISSUE THREAD

**Issue by DevBlocky** [blockba5her/dispatchsystem#4]
2 reports of Commands not working after usage of 5-30 times on server. Reported with no error messages within, so not a lot to go on. Will keep updated on this thread. 

**PRIORITY**

**Comment by DevBlocky** [comment]
UPDATE: Nothing so far, literally nothing. Still haven't been able to recreate the bug.

**Comment by DevBlocky** [comment]
UPDATE: New DUMP system being added to v2.1 for debugging. Also, v2.1 should fix the issue of the menu not closing.

**Comment by Toborgps** [comment]
You sure?

**Comment by DevBlocky** [comment]
UPDATE: Possible cause of issues could be GUID Nullification. Fixed in most recent commit. Will be pushed in v2.2

**Comment by DevBlocky** [comment]
Another Update: Issue might be fixed in the beta due to the resource being turned into 2 resources, will close for now but if more reports come in then I'm going to reopen.
